### ISSUE TITLE
Thermostat api endpoint have been Deprecated by netatmo

### ISSUE THREAD

**Issue by miawgogo** [jabesq/netatmo-api-python#25]
The api endpoints we are currently using are no longer supported by netatmo as on[ this page](https://dev.netatmo.com/en-US/resources/technical/reference/deprecated), the issue is that changing to the new API will have to be a breaking change.

**Comment by shanbs** [comment]
#26 PR does not use the the deprecated APIs any longer (The deprecated APIs have not yet been removed just for back-compatibility).
