### ISSUE TITLE
Add support for home schedule switch

### ISSUE THREAD

**Issue by royto** [jabesq/netatmo-api-python#46]
Netatmo energy support schedule. I personnaly has a default schedule and a guest one. 
Available schedule and selected one is already implemented in HomeData object

I'm using Home assistant and I want to switch schedule if I detect guests.

An [API is available to switch schedule]( https://dev.netatmo.com/en-US/resources/technical/reference/energy/switchhomeschedule)

I would be great to add support for this

**Comment by cgtobi** [comment]
I'll take that one.

**Comment by cgtobi** [comment]
Still needs to be implemented in HA.
