### ISSUE TITLE
Thermostat disconnected - error not catch

### ISSUE THREAD

**Issue by Mikado8231** [jabesq/netatmo-api-python#94]
Hi guys, 

I have an issue when my thermostat is disconnected (wifi connection lost...).

I analyse the json received from netatmo, the error tag is include in body, not at root level:
```
{ 
   'status':'ok',
   'body':{ 
      'errors':[ 
         { 
            'code':6,
            'id':'xx:xx:xx:xx:xx:xx'
         }
      ],
      'home':{ 
         'id':'xx'
      }
   },
   'time_server':xxx
}
```

In the thermostat.py, the error is checked in `resp` and not in `resp["body"]` ([after post_request](https://github.com/jabesq/netatmo-api-python/blob/master/src/pyatmo/thermostat.py#L168)):
`if "errors" in resp or "body" not in resp or "home" not in resp["body"]:`

I don't know if the case of error in root level exists...

Thanks.

**Comment by cgtobi** [comment]
Thanks for the feedback. We’ll take a look ASAP.

**Comment by cgtobi** [comment]
@Mikado8231 please let me know if you're available for testing. Best contact me on Discord/HA-Forum or any suggest another medium.

**Comment by Mikado8231** [comment]
@cgtobi yes I can try today.
I'm not an HA user. I can use the medium as you want.

**Comment by cgtobi** [comment]
Do you need an installable wheel or can you work with the source?

**Comment by Mikado8231** [comment]
I use library in standalone and I'm not a Python expert ;)

For the tests, I replaced thermostat.py by your fix file in my folder.
I have unplugged my thermostat and run my script. Exception is raise correctly. 

It's work fine.
Thanks.

**Comment by cgtobi** [comment]
Thanks for reporting this detailed issue and testing the fix.
